
import os
import sys

sconscript_link_path = os.path.join(os.getcwd(), 'SConscript')
sconscript_file_path = os.path.realpath(sconscript_link_path)
BUILDTOOL_PATH=os.path.dirname(os.path.dirname(sconscript_file_path))
sys.path.insert(0, BUILDTOOL_PATH)

from gscons.genode_sconstruct import sconstruct

sconstruct()
